// vue3/src/components/todolist.vue
<script setup>
import { ref } from "vue";

const list = ref([]);
const inp = ref('');
const isSet = ref(false);
const currentIndex = ref(-1);

function add() {  
    list.value.push(inp.value);
    // 清空输入框
    inp.value = '';
}

function onDelete(index) {  
    list.value.splice(index, 1);
}
function onSet(index) { 
    currentIndex.value = index;
    isSet.value = true;
}
</script>

<template>

    <input type="text" v-model.trim="inp">
    <button @click="add">新增</button>
    
    <ul>
        <li 
            v-for="(item, index) in list" 
            :key="index"
        >
        <input type="text" 
        v-if="isSet"
        v-model="inp"
        >
        <span v-else>
            {{ item }}
        </span>
        
        <button @click="onDelete(index)">
            删除
        </button>
        <button @click="onSet(index)">
            {{ isSet ? '提交' : '修改' }}
        </button>
        </li>
    </ul>
</template>

// my-react/my-react/src/components/todoList.tsx
import React from 'react'

export default class TodoList extends React.Component {
  protected isRevise = false;
  state = {
    inputValue: '',
    list: []
  };
  onInput(e: React.MouseEvent<HTMLInputElement>) {
    this.setState({
      inputValue: (e.target as HTMLInputElement).value
    })
  }
  // 增加
  onAdd(e: React.MouseEvent<HTMLButtonElement>) {
    this.setState({
      list: [...this.state.list, this.state.inputValue]
    })
  }
  // 删除
    onDelete(currentIndex: number){
        this.setState({
            list: this.state.list.filter((item, index) => index !== currentIndex)
        })
    }
  //   修改
    onRevise(currentIndex: number) {
      this.isRevise = true;
      this.setState({
          list: this.state.list.map((item, index) => {
              if (index === currentIndex) {
                  return <input type="text" />
              }
              return item
          })
      })
    }
  render() {
    return (
        <div>
          input: <input type="text" value={ this.state.inputValue} onInput={ this.onInput.bind(this)}/>
          <button onClick={this.onAdd.bind(this)}>增加</button>
          <ul>
            {
              this.state.list
                  .map((item, index) =>
                      <li key={index}>
                        {/*{ this.isRevise ? <input type="text" ref={'inp'}/> : {item}}*/}
                        <button onClick={ () => this.onDelete(index)}>删除</button>  // 箭头函数传参 箭头函数this指向声明时候的指向上下文
                        {/*<button onClick={ this.onDelete.bind(this, index)}>删除</button>  */} // bind 传参
                        <button onClick={ () => this.onRevise(index) }>修改</button>
                      </li>
                  )
            }
          </ul>
        </div>
    )
  }
}
