// day39echarts/react-class-echarts/src/components/echarts.jsx
import React from "react";
import * as echarts from "echarts";

// react class 写法

class Echarts extends React.Component {
  // componentDidMount() {
  //   const myChart = echarts.init(document.querySelector(".echarts"));
  //   myChart.setOption(this.props.option);
  // }
  // componentWillReceiveProps
  componentDidUpdate() {
    console.log(this.props.option.series[0]);
    const myChart = echarts.init(document.querySelector(".echarts"));
    myChart.setOption(this.props.option);
  }

  render() {
    return (
      <div
        className={"echarts"}
        style={{
          height: 500,
        }}
      ></div>
    );
  }
}

export default Echarts;

// import React from "react";
// import * as echarts from "echarts";
//
// export default class Computed extends React.Component {
//   // }
//   componentDidUpdate() {
//     const myChart = echarts.init(document.getElementById("main"));
//     myChart.setOption(this.props.option);
//   }
//
//   render() {
//     return <div id="main" style={{ width: 600, height: 400 }}></div>;
//   }
// }

// day39echarts/vue2-echarts/src/components/e-charts.vue
<template>
  <div>
    <div class="main"></div>
    <button @click="onChangeOption">点击切换数据</button>
  </div>
</template>

<script>
import * as echarts from "echarts";
// import { ref } from "vue";
//
// let option = ref();

let myChart = null;

export default {
  name: "e-charts",
  props: {
    option: {
      type: Object,
      default: () => ({}),
    },
  },
  methods: {
    onChangeOption() {
      this.$emit("changeOption");
      // myChart.setOption(this.option); // 这样写不行，因为option是ref类型，不能直接赋值
      // option.value = this.option;
      // myChart.setOption(option.value);
      myChart.setOption(this.option);
    },
  },
  mounted() {
    // 基于准备好的dom，初始化echarts实例
    myChart = echarts.init(document.querySelector(".main"));
    // option.value = this.option;
    // 绘制图表
    myChart.setOption(this.option);
  },
  // watch: {
  //   option(newValu) {
  //     myChart.setOption(newValu);
  //   },
  // },
};
</script>

<style scoped>
.main {
  width: 100%;
  height: 500px;
}
</style>
