// day39echarts/vue3-echarts/src/components/echarts.vue
<script setup>
import { ref, onMounted } from "vue";
import * as echarts from "echarts";

const props = defineProps({
  options: {
    type: Object,
    default: () => ({}),
  },
});
// 接收父组件传过来的方法
const emit = defineEmits(["onChangeOption"]);

let myChart;

function onClick() {
  emit("onChangeOption");
  console.log(props.options.series[0].data);
  myChart.setOption(props.options);
}

onMounted(() => {
  console.log(props.options);
  console.log(document.querySelector(".echarts"));
  // $emit(
  //   "onChangeOption",
  //   props.options.series[0].map(() => Math.floor(Math.random() * 100))
  // );
  // 基于准备好的dom，初始化echarts实例
  myChart = echarts.init(document.querySelector(".echarts"));
  // 绘制图表
  console.log(props.options);
  myChart.setOption(props.options);
});
</script>

<template>
  <div class="echarts"></div>
  <button @click="onClick">点击改变数据</button>
</template>

<style scoped>
.echarts {
  width: 100%;
  height: 500px;
  outline: 1px red solid;
}
</style>

// day39echarts/react-class-echarts/src/components/echarts.jsx
import React from "react";
import * as echarts from "echarts";

// react class 写法

class Echarts extends React.Component {
  // componentDidMount() {
  //   const myChart = echarts.init(document.querySelector(".echarts"));
  //   myChart.setOption(this.props.option);
  // }
  // componentWillReceiveProps
  componentDidUpdate() {
    console.log(this.props.option.series[0]);
    const myChart = echarts.init(document.querySelector(".echarts"));
    myChart.setOption(this.props.option);
  }

  render() {
    return (
      <div
        className={"echarts"}
        style={{
          height: 500,
        }}
      ></div>
    );
  }
}

export default Echarts;

// import React from "react";
// import * as echarts from "echarts";
//
// export default class Computed extends React.Component {
//   // }
//   componentDidUpdate() {
//     const myChart = echarts.init(document.getElementById("main"));
//     myChart.setOption(this.props.option);
//   }
//
//   render() {
//     return <div id="main" style={{ width: 600, height: 400 }}></div>;
//   }
// }
